### ISSUE TITLE
Update latest issues for all the journals

### ISSUE THREAD

**Issue by Shruthisdst** [SrirangaDigital/ias#112]
Bulletin of Materials Science - June 2015 - To be updated.
Journal of Astrophysics and Astronomy  - No updates.
Journal of Biosciences - No updates.
Journal of Chemical Sciences - May and June 2015 - To be updated.
Journal of Earth System Science - July 2015 - To be updated.
Journal of Genetics - June 2015 - To be updated.
Pramana Journal of Physics - July and August 2015 - To be updated.
Proceedings Mathematical Sciences - No updates.
Resonance - No updates.
Sadhana - May and June 2015 - To be updated.

Work to be done
1) XML -> Data entry -> Raghu and Prathibha
2) Downloading pdf and renaming -> Bhagyalakshmi
3) Inserting data into database
4) Thumbnails for current issues

**Comment by arjunkashyap** [comment]
Has this been done? We need to close this issue soon.

**Comment by arjunkashyap** [comment]
Has this been done? We need to close this issue soon.

**Comment by arjunkashyap** [comment]
Done. dB regenerated.
