### ISSUE TITLE
Warning displaying in bibliography of authors page

### ISSUE THREAD

**Issue by Shruthisdst** [SrirangaDigital/ias#123]
When clicking any of the authorname in TOC page then warning message displaying like 
Strict Standards: Only variables should be passed by reference in /var/www/ias/application/models/listingModel.php on line 83

Eg: http://192.168.1.24/ias/public/listing/bibliography/boms/K._N._Madhusoodanan

![screenshot from 2015-08-18 17 24 20](https://cloud.githubusercontent.com/assets/9712072/9329323/1665e634-45ce-11e5-8d22-529ca66122bd.png)

**Comment by arjunkashyap** [comment]
Rectified. Please verify once before closing this issue.

**Comment by Shruthisdst** [comment]
No warnings
