### ISSUE TITLE
Check if following files are there in the missing page/pdf list

### ISSUE THREAD

**Issue by arjunkashyap** [SrirangaDigital/ias#155]
jess/109/01/0022-0038.txt
reso/009/11/0099-0099.txt
reso/011/11/0040-0047.txt 40 page missing
reso/018/12/1165-1165.txt
reso/018/12/1166-1166.txt
reso/019/05/0483-0483.txt
reso/019/05/0484-0484.txt

**Comment by Shruthisdst** [comment]
jess/109/01/0022-0038.txt -> It is there in missing list.
reso/009/11/0099-0099.txt -> It is not there in missing list but there in Problems list.
reso/011/11/0040-0047.txt 40 page missing -> It is not there in missing list but there in Problems list.
reso/018/12/1165-1165.txt - > It is there in missing list.
reso/018/12/1166-1166.txt ->  It is there in missing list.
reso/019/05/0483-0483.txt -> Page not missing (Available in Bhagyalakshmi system)
reso/019/05/0484-0484.txt -> Page not missing (Available in Bhagyalakshmi system)
