### ISSUE TITLE
Information about Public and Special lectures

### ISSUE THREAD

**Issue by arjunkashyap** [SrirangaDigital/ias#165]
Add to the 'Public and Special lectures in mid-year and annual meetings' page Public and Special lectures from: annual meeting 2013, mid-year meeting 2014, annual meeting 2014, mid-year meeting 2015? The lecture titles and speaker names should be available in the meeting programme files.

http://localhost/ias/public/page/flat/Events/Public_Lectures/Public_Lectures

**Comment by Shruthisdst** [comment]
Done
