### ISSUE TITLE
Update october 2015 issue for Bulletin of Materials Science

### ISSUE THREAD

**Issue by Shruthisdst** [SrirangaDigital/ias#173]
Download pdf files
Renaming of downloaded pdf files.
Preparing XML for the issue to be updated.
Extracting text from these pdf files.
Downloading cover page for current issues to be updated.
Check the links

**Comment by Shruthisdst** [comment]
Download and Renaming of pdf files completed

**Comment by shivasdst** [comment]
Uploaded pdf files to current science server as well as production server.

**Comment by Shruthisdst** [comment]
XML and links checking completed
