### ISSUE TITLE
Update September 2015 issue for Journal of Chemical Sciences

### ISSUE THREAD

**Issue by shivasdst** [SrirangaDigital/ias#175]
Download pdf files
Renaming of downloaded pdf files.
Preparing XML for the issue to be updated.
Extracting text from these pdf files.
Downloading cover page for current issues to be updated.
Check the links

**Comment by Shruthisdst** [comment]
Downloa and Renaming of  pdf files completed

**Comment by Shruthisdst** [comment]
XML completed

**Comment by Shruthisdst** [comment]
XML checking completed

**Comment by Shruthisdst** [comment]
PDF link checking done
