### ISSUE TITLE
While inserting journal of chemical sciences into the database we are getting warnings and notices

### ISSUE THREAD

**Issue by bhagyasdst** [SrirangaDigital/ias#18]
ex:
Warning: simplexml_load_file(): http://localhost/ias/md-src/xml/jcsc.xml:50522: parser error : CharRef: invalid decimal value in /var/www/ias/application/models/dataModel.php on line 22

Warning: simplexml_load_file(): (BH<sub>3</sub>)N(2,6-<sub>i</sub>Pr<sub>2</sub>C<sub>6</sub>H<sub>6</sub>)&#125 in /var/www/ias/application/models/dataModel.php on line 22

Warning: simplexml_load_file(): ^ in /var/www/ias/application/models/dataModel.php on line 22

Warning: simplexml_load_file(): http://localhost/ias/md-src/xml/jcsc.xml:50522: parser error : xmlParseCharRef: invalid xmlChar value 0 in /var/www/ias/application/models/dataModel.php on line 22

Warning: simplexml_load_file(): (BH<sub>3</sub>)N(2,6-<sub>i</sub>Pr<sub>2</sub>C<sub>6</sub>H<sub>6</sub>)&#125 in /var/www/ias/application/models/dataModel.php on line 22

Warning: simplexml_load_file(): ^ in /var/www/ias/application/models/dataModel.php on line 22

Notice: Trying to get property of non-object in /var/www/ias/application/models/dataModel.php on line 25

Warning: Invalid argument supplied for foreach() in /var/www/ias/application/models/dataModel.php on line 25

**Comment by arjunkashyap** [comment]
Resolved.
