### ISSUE TITLE
Fellowship search division not displaying properly 

### ISSUE THREAD

**Issue by Shruthisdst** [SrirangaDigital/ias#187]
In Fellowship page, in search part 'Section' not displaying properly.
![screenshot from 2015-12-30 10 53 49](https://cloud.githubusercontent.com/assets/9712072/12046752/0ea0134a-aee5-11e5-9b29-19f6f1031895.png)
![screenshot from 2015-12-30 10 54 37](https://cloud.githubusercontent.com/assets/9712072/12046755/14915ade-aee5-11e5-925d-ea152ac0067a.png)

**Comment by arjunkashyap** [comment]
Fixed.
