### ISSUE TITLE
Bug in forthcoming articles and regular articles display

### ISSUE THREAD

**Issue by shivasdst** [SrirangaDigital/ias#189]
Following list of tags and their equivalents have to be replaced while displaying forthcoming articles as well as published articles.

```
<list list-type="bullet">, <ul>
</list>, </ul>

<list list-type="ordered">, <ol>
</list>, </ol>

<list-item><p>, <li>
</p></list-item>, </li>

<italic>, <i>
</italic>, </i>

<bold>, <b>
</bold>, </b>

<underline>, <u>
</underline>, </u>
```

**Comment by arjunkashyap** [comment]
Shivu, this has been dealt with in your script now right?

**Comment by shivasdst** [comment]
Yes Arjun. Already I have handled them in my xml generation script.  
I think we have to handle them in the display(let me check).

**Comment by arjunkashyap** [comment]
I will be closing this issue @shivasdst Please reopen the issue if you feel it is unsolved.
