### ISSUE TITLE
subscript, superscript, bold  and italic these are not working in display of title and keywords

### ISSUE THREAD

**Issue by bhagyasdst** [SrirangaDigital/ias#3]
For ex:
http://localhost/ias/public/describe/article/sadh/039/03/0731-0764
and 
http://localhost/ias/public/describe/article/sadh/039/03/0699-0711

**Comment by arjunkashyap** [comment]
Could you please attach a screenshot describing the error.

**Comment by arjunkashyap** [comment]
Solved while closing other bugs. Please reopen this with proper screenshot if bug is rediscovered.
