### ISSUE TITLE
Prepare spread sheet showing urls to existing website

### ISSUE THREAD

**Issue by shivasdst** [SrirangaDigital/ias#77]
Preparing a spread sheet having two columns.

1) New website page
2) Existing website url

Each column will contain URLs.  URL in first column indicates page containing 2nd URL.
This help IAS people to move some of those resources to subdomain.

**Comment by arjunkashyap** [comment]
Done.
Available at https://docs.google.com/spreadsheets/d/1gcO8T22aqHvCSizivkCh0nL5m0cwavrY3MaY8YwrRt4/edit?usp=sharing
